// Mock data for development when API is not available
export const mockJobs = [
  {
    _id: '1',
    company: 'Google',
    position: 'Frontend Developer',
    location: 'Mountain View, CA',
    status: 'Applied',
    applicationDate: new Date('2023-04-01'),
    jobDescription: 'Working on Google Search frontend',
    notes: 'Applied through referral',
    salary: '$120,000 - $150,000',
    jobType: 'Full-time',
    url: 'https://careers.google.com',
    contactName: 'John Recruiter',
    contactEmail: 'john@google.com',
    contactPhone: '123-456-7890',
  },
  {
    _id: '2',
    company: 'Microsoft',
    position: 'Software Engineer',
    location: 'Redmond, WA',
    status: 'Interview',
    applicationDate: new Date('2023-03-15'),
    jobDescription: 'Working on Microsoft Teams',
    notes: 'First interview scheduled for next week',
    salary: '$125,000 - $160,000',
    jobType: 'Full-time',
    url: 'https://careers.microsoft.com',
    contactName: 'Sarah Recruiter',
    contactEmail: 'sarah@microsoft.com',
    contactPhone: '123-456-7891',
  },
  {
    _id: '3',
    company: 'Amazon',
    position: 'Full Stack Developer',
    location: 'Seattle, WA',
    status: 'Offer',
    applicationDate: new Date('2023-02-28'),
    jobDescription: 'Working on AWS services',
    notes: 'Received offer, negotiating salary',
    salary: '$130,000 - $165,000',
    jobType: 'Full-time',
    url: 'https://careers.amazon.com',
    contactName: 'Mike Recruiter',
    contactEmail: 'mike@amazon.com',
    contactPhone: '123-456-7892',
  },
  {
    _id: '4',
    company: 'Facebook',
    position: 'React Developer',
    location: 'Menlo Park, CA',
    status: 'Rejected',
    applicationDate: new Date('2023-02-15'),
    jobDescription: 'Working on Facebook News Feed',
    notes: 'Rejected after second interview',
    salary: '$135,000 - $170,000',
    jobType: 'Full-time',
    url: 'https://careers.facebook.com',
    contactName: 'Lisa Recruiter',
    contactEmail: 'lisa@facebook.com',
    contactPhone: '123-456-7893',
  },
  {
    _id: '5',
    company: 'Netflix',
    position: 'Senior Frontend Engineer',
    location: 'Los Gatos, CA',
    status: 'Saved',
    applicationDate: new Date('2023-04-05'),
    jobDescription: 'Working on Netflix streaming UI',
    notes: 'Interesting position, will apply soon',
    salary: '$140,000 - $180,000',
    jobType: 'Full-time',
    url: 'https://careers.netflix.com',
    contactName: 'David Recruiter',
    contactEmail: 'david@netflix.com',
    contactPhone: '123-456-7894',
  },
];

export const mockUser = {
  _id: '1',
  name: 'Test User',
  email: 'testuser@example.com',
};

// Mock stats
export const mockStats = {
  applied: 1,
  interview: 1,
  offer: 1,
  rejected: 1,
  saved: 1,
}; 